### ISSUE TITLE
issue with how the games are being opened, they're not being opened

### ISSUE THREAD

**Issue by DoxrGitHub** [FoxMoss/FoxLauncher#2]
clicking the bookmarked games doesn't open it, you have to drag the link into the tab in order for it to work.

**Comment by FoxMoss** [comment]
thats a limit of the filesystem api, i mention that in the docs maybe should've made it more clear. with the tab perms on chrome extensions you can open them, but i havent figured out a work around without. maybe submit it as a bug to the chrome source?
